/* Chapitre 11-Views*/
/*--------------EX-1----------------*/

CREATE VIEW EMP_VU2 
AS SELECT EMPNO, ENAME EMPLOYEE, DEPTNO 
FROM EMP;

SELECT * FROM EMP_VU2;

/*--------------EX-2----------------*/

SELECT EMPLOYEE ,DEPTNO FROM EMP_VU2;
/*--------------EX-3----------------*/

CREATE VIEW DEPT20
AS SELECT EMPNO 'EMPLOYEE_ID', ENAME 'EMPLOYEE', DEPTNO 'DEPARTEMENT_ID'
FROM EMP 
WHERE DEPTNO = 20
WITH CHECK OPTION ; 
SELECT * FROM EMP;

/*--------------EX-4----------------*/

sp_columns DEPT20
SELECT * FROM DEPT20;

UPDATE DEPT20
SET DEPARTEMENT_ID = 30
WHERE EMPLOYEE = 'SMITH';



/*--------------EX-5----------------*/
CREATE VIEW SALARY_VU
AS SELECT  e.ENAME 'EMPLOYEE', e.DEPTNO 'DEPARTEMENT_ID', e.SAL SALARY,  s.GRADE GRADE
FROM EMP e, SALGRADE s 
WITH CHECK OPTION; 

SELECT * FROM SALARY_VU

